#!/usr/bin/python
# -*- coding: latin-1 -*-

from api import session
from api.models import IngredientRecipe, Ingredient

# update tb_ingredient with names from our curated list
# update ingredient fk in tb_ingredient_recipe to point back to the updated ingredient.
# Ensures only one properly named ingredient exists in tb_ingredient
def extract_ingredient_names(ingredient_names):
    # keeps track of changes to ingredients and ingredients we couldn't find names for
    changes = {}
    changes['changed'] = []
    changes['failure'] = []

    ingredients = session.query(Ingredient).all()
    print "Ingredients Count: " + str(len(ingredients))
    for old_ingredient in ingredients:

        is_changed = False
        # We can't use tb_ingredient.name since those have been shortened beyond usage (ex. cube instead of ice cube)
        # Instead use a description from tb_ingredient_recipe
        candidate_name = old_ingredient.ingredient_recipe[0].description
        # Compare each proper name to the old name
        old_name = old_ingredient.ingredient_recipe[0].description

        for clean_ingredient_name in ingredient_names:
            # if we find a clean version of the ingredient name (i.e chicken breast vs quartered chicken breasts oiled),
            # use the clean version. In the case where we have already replaced the given ingredient name, only override
            # the replacement if the new version is longer (i.e. start with chicken vs quarted chicken breasts, then chicken breasts).
            try:
                if clean_ingredient_name in old_name and (not is_changed or len(clean_ingredient_name) > len(candidate_name)):
                    candidate_name = clean_ingredient_name
                    is_changed = True
            except:
                # TODO fix unicode issues
                pass

        if not is_changed:
            changes['failure'].append(candidate_name)
        else:
            # Check if an ingredient already has this name (We don't want 2 chicken breasts in tb_ingredient)
            existing_ingredient = session.query(Ingredient).filter_by(name = candidate_name).first()

            if old_ingredient.name != candidate_name:
                changes['changed'].append(old_ingredient.name + " -> " + candidate_name)

            if existing_ingredient is None:
                old_ingredient.name = candidate_name
                print("Cleaned ingredient " + str(candidate_name))
            else:
                # Correct the references in tb_ingredient_recipe

                # For tracking how many ingredient_recipes we change
                old_ingredient_recipes_count = session.query(IngredientRecipe). \
                    filter_by(ingredient_fk = existing_ingredient.ingredient_pk).count()

                # Points the ingredient_recipe's for the updated ingredient to the previously existing properly named ingredient
                old_ingredient_recipes = session.query(IngredientRecipe). \
                    filter(IngredientRecipe.ingredient_fk == old_ingredient.ingredient_pk)

                for old_ingredient_recipe in old_ingredient_recipes:
                    old_ingredient_recipe.ingredient_fk = existing_ingredient.ingredient_pk

                # no longer needed since we updated the corresponding ingredient_recipes to point
                # to an ingredient with the same "proper" name
                session.delete(old_ingredient)
                print "old ingredient " + str(old_ingredient.as_dict())
                print "existing ingredient " + str(existing_ingredient.as_dict())
                session.commit()
                return

                new_ingredient_recipes_count = session.query(IngredientRecipe). \
                    filter_by(ingredient_fk = existing_ingredient.ingredient_pk).count()

                print("Existing ingredient " + str(existing_ingredient.name) + " changed: " + str(new_ingredient_recipes_count - old_ingredient_recipes_count))

    return changes

curated_ingredient_names = [
    "hot pepper sauce",
    "tomato sauce",
    "bell pepper",
    "sour cream",
    "kalamata olives",
    "crabmeat",
    "green onions",
    "garlic salt",
    "garlic powder",
    "flank steak",
    "feta cheese",
    "adobo sauce",
    "chicken bouillon",
    "salad dressing",
    "acai berry",
    "margarita mix",
    "corn flakes",
    "corn tortillas",
    "enchilada sauce",
    "frozen strawberries",
    "green chiles",
    "sake",
    "sauerkraut drained",
    "vanilla yogurt",
    "water",
    "zucchini",
    "water",
    "ackee",
    "acorn squash",
    "aduki beans",
    "advocaat",
    "agar-agar",
    "ale",
    "alfalfa sprouts",
    "allspice",
    "almond",
    "almond essence",
    "almond extract",
    "almond milk",
    "amaranth",
    "amaretti",
    "anchovies",
    "anchovy essence",
    "angelica",
    "angostura bitters",
    "anise",
    "apple",
    "apple chutney",
    "apple juice",
    "apple sauce",
    "apricot",
    "apricot jam",
    "arborio rice",
    "arbroath smokie",
    "argan oil",
    "arrowroot",
    "artichoke",
    "asafoetida",
    "asparagus",
    "aubergine",
    "avocado",
    "bacon",
    "bagel",
    "baguette",
    "baked beans",
    "baking",
    "baking powder",
    "balsamic vinegar",
    "bamboo shoots",
    "banana",
    "banana bread",
    "barbary duck",
    "barbecue sauce",
    "barley",
    "basil",
    "basmati rice",
    "bay boletes",
    "bay leaf",
    "beans",
    "beansprouts",
    "bechamel sauce",
    "beef",
    "beef consommé",
    "beef dripping",
    "beef mince",
    "beef ribs",
    "beef rump",
    "beef sausage",
    "beef stock",
    "beef tomato",
    "beer",
    "beetroot",
    "berry",
    "betel leaves",
    "beurre manié",
    "bicarbonate of soda",
    "bilberries",
    "bird's-eye chillies",
    "biscotti",
    "biscuits",
    "blachan",
    "black beans",
    "black bream",
    "black eyed beans",
    "black pepper",
    "black pudding",
    "black sesame seeds",
    "black treacle",
    "blackbean sauce",
    "blackberry",
    "blackcurrant",
    "blackcurrant juice drink",
    "blini",
    "blood orange",
    "blueberry",
    "boar",
    "bok choi",
    "bonito",
    "borage",
    "borlotti beans",
    "bouquet garni",
    "braising steak",
    "bramley apple",
    "bran",
    "brandy",
    "brandy butter",
    "brandy snaps",
    "bratwurst",
    "brazil nut",
    "bread",
    "bread roll",
    "bread sauce",
    "breadcrumbs",
    "breadfruit",
    "breadsticks",
    "bresaola",
    "brie",
    "brill",
    "brioche",
    "brisket",
    "broad beans",
    "broccoli",
    "broth",
    "brown bread",
    "brown lentil",
    "brown rice",
    "brown sauce",
    "brown shrimp",
    "brown sugar",
    "brussels sprouts",
    "buckwheat",
    "buckwheat flour",
    "bulgur wheat",
    "buns",
    "burger",
    "butter",
    "butter beans",
    "buttercream icing",
    "butterhead lettuce",
    "buttermilk",
    "butternut squash",
    "cabbage",
    "caerphilly",
    "cake",
    "calasparra rice",
    "calvados",
    "camembert",
    "campagne loaf",
    "candied peel",
    "cannellini beans",
    "cape gooseberries",
    "capers",
    "capsicum",
    "caramel",
    "caraway seeds",
    "cardamom",
    "carob",
    "carrageen moss",
    "carrageen_moss",
    "carrot",
    "cashew",
    "cassava",
    "caster sugar",
    "catfish",
    "caul fat",
    "cauliflower",
    "cava",
    "caviar",
    "cavolo nero",
    "cayenne pepper",
    "celeriac",
    "celery",
    "celery seeds",
    "champ",
    "champagne",
    "chanterelle mushrooms",
    "chantilly cream",
    "chapati flour",
    "chapatis",
    "charcuterie",
    "chard",
    "charlotte potato",
    "chayote",
    "cheddar",
    "cheese",
    "cheese sauce",
    "cherry",
    "cherry brandy",
    "cherry tomatoes",
    "chervil",
    "cheshire",
    "chestnut",
    "chestnut mushrooms",
    "chicken",
    "chicken breast",
    "chicken leg",
    "chicken liver",
    "chicken soup",
    "chicken stock",
    "chicken thigh",
    "chicken wing",
    "chickpea",
    "chickpea flour",
    "chicory",
    "chilli",
    "chilli con carne",
    "chilli oil",
    "chilli paste",
    "chilli powder",
    "chilli sauce",
    "chinese cabbage",
    "chinese mushrooms",
    "chinese pancake",
    "chipotle",
    "chips",
    "chives",
    "chocolate",
    "chocolate biscuit",
    "chocolate brownies",
    "chocolate cake",
    "chocolate mousse",
    "chocolate truffle",
    "chopped tomatoes",
    "chorizo",
    "choux pastry",
    "christmas cake",
    "christmas pudding",
    "chuck and blade",
    "chump",
    "chutney",
    "ciabatta",
    "cider",
    "cinnamon",
    "citrus fruit",
    "clams",
    "clarified butter",
    "clementine",
    "clotted cream",
    "cloves",
    "cobnut",
    "cockles",
    "cocktail",
    "cocoa butter",
    "cocoa powder",
    "coconut",
    "coconut cream",
    "coconut milk",
    "coconut oil",
    "cod",
    "cod roe",
    "coffee",
    "coffee beans",
    "coffee essence",
    "coffee granules",
    "coffee liqueur",
    "cognac",
    "cola",
    "coleslaw",
    "coley",
    "collar",
    "compôte",
    "comté",
    "condensed milk",
    "confectionery",
    "coriander",
    "coriander cress",
    "coriander seeds",
    "corn oil",
    "corn syrup",
    "corned beef",
    "cornflour",
    "cos lettuce",
    "cottage cheese",
    "coulis",
    "courgette",
    "court bouillon",
    "couscous",
    "crab",
    "crab apple",
    "crackers",
    "cranberry",
    "cranberry juice",
    "cranberry sauce",
    "crayfish",
    "cream",
    "cream cheese",
    "cream liqueur",
    "cream of tartar",
    "cream soda",
    "creamed coconut",
    "crème fraîche",
    "crêpe",
    "cress",
    "crispbread",
    "crisps",
    "croissant",
    "crostini",
    "croûtons",
    "crudités",
    "crumble",
    "crystallised ginger",
    "cucumber",
    "cumberland sauce",
    "cumin",
    "curacao",
    "curd",
    "curd cheese",
    "curly kale",
    "currant bread",
    "currants",
    "curry",
    "curry leaves",
    "curry paste",
    "curry powder",
    "custard",
    "custard powder",
    "cuttlefish",
    "dab",
    "daikon",
    "damsons",
    "dandelion",
    "danish blue",
    "dark chocolate",
    "date",
    "demerara sugar",
    "demi-glace sauce",
    "desiccated coconut",
    "desirée",
    "digestive biscuit",
    "dijon mustard",
    "dill",
    "dim sum wrappers",
    "dolcelatte",
    "double cream",
    "double Gloucester",
    "dover sole",
    "dragon fruit",
    "dried apricots",
    "dried cherries",
    "dried chilli",
    "dried fruit",
    "dried mixed fruit",
    "dry sherry",
    "duck",
    "duck confit",
    "duck fat",
    "dulce de leche",
    "dumplings",
    "duxelles",
    "edam",
    "eel",
    "egg",
    "egg wash",
    "egg white",
    "egg yolk",
    "elderberries",
    "elderflower",
    "emmental",
    "english muffin",
    "english mustard",
    "escalope",
    "evaporated milk",
    "exotic fruit",
    "falafel",
    "farfalle",
    "fat",
    "fennel",
    "fennel seeds",
    "fenugreek",
    "feta",
    "fettuccine",
    "field mushroom",
    "fig",
    "fillet of beef",
    "filo pastry",
    "fish",
    "fish roe",
    "fish sauce",
    "fish soup",
    "five-spice powder",
    "flageolet beans",
    "flaked almonds",
    "flank",
    "flapjacks",
    "flatbread",
    "flatfish",
    "fleur de sel",
    "flour",
    "flour tortilla",
    "floury potato",
    "flying fish",
    "focaccia",
    "foie gras",
    "fondant icing",
    "fondant potatoes",
    "fontina cheese",
    "food colouring",
    "forced rhubarb",
    "fortified wine",
    "fragrant rice",
    "frangipane",
    "frankfurter",
    "freekeh",
    "french beans",
    "french bread",
    "french dressing",
    "fresh coriander",
    "fresh tuna",
    "fromage frais",
    "fruit",
    "fruit brandy",
    "fruit cake",
    "fruit juice",
    "fruit salad",
    "fudge",
    "fusilli",
    "galangal",
    "game",
    "gammon",
    "garam masala",
    "garlic",
    "garlic and herb cream cheese",
    "garlic bread",
    "gelatine",
    "ghee",
    "gherkin",
    "giblets",
    "gin",
    "ginger",
    "ginger ale",
    "ginger beer",
    "ginger biscuit",
    "gingerbread",
    "glacé cherries",
    "globe artichoke",
    "glucose",
    "gnocchi",
    "goats' cheese",
    "goats' milk",
    "golden syrup",
    "goose",
    "goose fat",
    "gooseberry",
    "gorgonzola",
    "gouda",
    "grain",
    "grape juice",
    "grapefruit",
    "grapefruit juice",
    "grapes",
    "grapeseed oil",
    "gratin",
    "gravy",
    "gravy browning",
    "green banana",
    "green beans",
    "green cabbage",
    "green lentil",
    "green tea",
    "greengages",
    "grey mullet",
    "ground almonds",
    "ground ginger",
    "grouse",
    "gruyère",
    "guacamole",
    "guava",
    "guinea fowl",
    "gurnard",
    "habañero chillies",
    "haddock",
    "haggis",
    "hake",
    "halibut",
    "halloumi",
    "ham",
    "hare",
    "haricot beans",
    "harissa",
    "hazelnut",
    "hazelnut oil",
    "heart",
    "herbal liqueur",
    "herbal tea",
    "herbes de provence",
    "herbs",
    "herring",
    "hogget",
    "hoisin sauce",
    "hoki",
    "hollandaise sauce",
    "hominy",
    "honey",
    "honeycomb",
    "horseradish",
    "horseradish sauce",
    "hot cross buns",
    "hummus",
    "hunza apricots",
    "ice cream",
    "iceberg lettuce",
    "icing",
    "icing sugar",
    "irish stout",
    "jaggery",
    "jam",
    "january King cabbage",
    "japanese pumpkin",
    "jelly",
    "jerk seasoning",
    "jersey Royal potatoes",
    "jerusalem artichoke",
    "john Dory",
    "jujube",
    "juniper berries",
    "jus",
    "kabana",
    "kale",
    "ketchup",
    "ketjap manis",
    "kidney",
    "kidney beans",
    "king Edward",
    "kipper",
    "kirsch",
    "kiwi fruit",
    "kohlrabi",
    "kumquat",
    "lager",
    "lamb",
    "lamb breast",
    "lamb chop",
    "lamb fillet",
    "lamb kidney",
    "lamb loin",
    "lamb mince",
    "lamb neck",
    "lamb rump",
    "lamb shank",
    "lamb shoulder",
    "lamb stock",
    "lancashire",
    "langoustine",
    "lard",
    "lardons",
    "lasagne",
    "lasagne sheets",
    "laverbread",
    "leek",
    "leftover turkey",
    "leg of lamb",
    "lemon",
    "lemon balm",
    "lemon curd",
    "lemon juice",
    "lemon sole",
    "lemonade",
    "lemongrass",
    "lentils",
    "lettuce",
    "lime",
    "lime cordial",
    "lime juice",
    "lime leaves",
    "lime pickle",
    "ling",
    "lingonberry",
    "linguine",
    "liqueur",
    "liquorice",
    "little Gem lettuce",
    "liver",
    "loaf cake",
    "lobster",
    "loganberry",
    "long-grain rice",
    "lovage",
    "lychee",
    "macadamia",
    "macaroni",
    "macaroon",
    "mace",
    "mackerel",
    "madeira",
    "madeira cake",
    "madeleines",
    "maize",
    "malted grain bread",
    "manchego",
    "mandarin",
    "mangetout",
    "mango",
    "mango chutney",
    "mango juice",
    "mango pickle",
    "mangosteen",
    "maple syrup",
    "margarine",
    "marjoram",
    "marmalade",
    "marrow",
    "marrowfat peas",
    "marsala wine",
    "marshmallow",
    "marzipan",
    "mascarpone",
    "mashed potato",
    "matzo",
    "mayonnaise",
    "meat",
    "medlars",
    "megrim",
    "melon",
    "melon seeds",
    "meringue",
    "mesclun",
    "milk",
    "milk chocolate",
    "milkshake",
    "millet",
    "millet flour",
    "mince",
    "mince pies",
    "mincemeat",
    "mint",
    "mint sauce",
    "mirepoix",
    "mirin",
    "miso",
    "mixed berries",
    "mixed dried beans",
    "mixed fish",
    "mixed nuts",
    "mixed spice",
    "mixed spices",
    "molasses",
    "monk's beard",
    "monkfish",
    "morel",
    "mortadella",
    "mozzarella",
    "muesli",
    "muffins",
    "mulberries",
    "mulled wine",
    "mung beans",
    "mushroom",
    "mussels",
    "mustard",
    "mustard cress",
    "mustard leaves",
    "mustard oil",
    "mustard powder",
    "mustard seeds",
    "mutton",
    "naan bread",
    "nachos",
    "nashi",
    "nasturtium",
    "nectarine",
    "nettle",
    "new potatoes",
    "nibbed almonds",
    "noodle soup",
    "noodles",
    "nori",
    "nougat",
    "nut",
    "nutmeg",
    "naan bread",
    "nachos",
    "nashi",
    "nasturtium",
    "nectarine",
    "nettle",
    "new potatoes",
    "nibbed almonds",
    "noodle soup",
    "noodles",
    "nori",
    "nougat",
    "nut",
    "nutmeg",
    "oatcakes",
    "oatmeal",
    "oats",
    "octopus",
    "offal",
    "oil",
    "oily fish",
    "okra",
    "olive",
    "olive oil",
    "onion",
    "orange",
    "orange juice",
    "orange liqueur",
    "oregano",
    "ouzo",
    "oxtail",
    "oyster",
    "oyster mushrooms",
    "oyster sauce",
    "paella",
    "pak choi",
    "palm sugar",
    "pancakes",
    "pancetta",
    "pandan leaves",
    "paneer",
    "panettone",
    "papaya",
    "pappardelle",
    "paprika",
    "parfait",
    "parmesan",
    "parsley",
    "parsnip",
    "partridge",
    "passata",
    "passion fruit",
    "passion fruit juice",
    "pasta",
    "pastrami",
    "pastry",
    "pasty",
    "pâté",
    "paw-paw",
    "pea shoots",
    "peach",
    "peanut butter",
    "peanut oil",
    "peanuts",
    "pear",
    "pearl barley",
    "peas",
    "pecan",
    "pecorino",
    "pectin",
    "peel",
    "penne",
    "pepper",
    "peppercorn",
    "pepperoni",
    "perch",
    "perry",
    "pesto",
    "pheasant",
    "piccalilli",
    "pickle",
    "pickled onion",
    "pie",
    "pig cheeks",
    "pigeon",
    "pigeon peas",
    "pike",
    "pine nut",
    "pineapple",
    "pineapple juice",
    "pink Fir Apple",
    "pink peppercorn",
    "pinto beans",
    "piri-piri",
    "pistachio",
    "pitta bread",
    "pizza",
    "plaice",
    "plain flour",
    "plantain",
    "plum",
    "polenta",
    "pollack",
    "pollock",
    "pomegranate",
    "pomegranate juice",
    "pomegranate molasses",
    "pomelo",
    "popcorn",
    "poppy seeds",
    "porcini",
    "pork",
    "pork belly",
    "pork chop",
    "pork fillet",
    "pork leg",
    "pork loin",
    "pork mince",
    "pork sausages",
    "pork shoulder",
    "pork spare rib",
    "port",
    "portobello mushrooms",
    "potato",
    "potato rösti",
    "potato wedges",
    "poultry",
    "poussin",
    "praline",
    "prawn",
    "prawn crackers",
    "preserved lemons",
    "preserves",
    "prosciutto",
    "prune",
    "prune juice",
    "pudding rice",
    "puff pastry",
    "pulled pork",
    "pulse",
    "pumpernickel bread",
    "pumpkin",
    "pumpkin seed",
    "purple sprouting broccoli",
    "puy lentils",
    "quail",
    "quails' egg",
    "quark",
    "quatre-épices",
    "quince",
    "quinoa",
    "rabbit",
    "rack of lamb",
    "radicchio",
    "radish",
    "rainbow chard",
    "rainbow trout",
    "raisins",
    "raita",
    "rapeseed oil",
    "ras-el-hanout",
    "raspberry",
    "raspberry jam",
    "ratafia biscuits",
    "ratatouille",
    "red cabbage",
    "red Leicester",
    "red lentil",
    "red mullet",
    "red onion",
    "red rice",
    "red snapper",
    "red wine",
    "red wine vinegar",
    "redcurrant",
    "redcurrant jelly",
    "rennet",
    "rhubarb",
    "rib of beef",
    "rice",
    "rice flour",
    "rice noodles",
    "rice pudding",
    "rice vinegar",
    "rice wine",
    "ricotta",
    "rigatoni",
    "risotto",
    "risotto rice",
    "roast beef",
    "roast chicken",
    "roast lamb",
    "roast pork",
    "roast potatoes",
    "roast turkey",
    "roasted vegetables",
    "rock salmon",
    "rock salt",
    "rocket",
    "root beer",
    "root vegetable",
    "roquefort",
    "rose wine",
    "rosehip syrup",
    "rosemary",
    "rosewater",
    "rouille",
    "royal icing",
    "rum",
    "rump",
    "runner beans",
    "rye bread",
    "rye flour",
    "safflower oil",
    "saffron",
    "sage",
    "salad",
    "salad cream",
    "salad leaves",
    "salami",
    "salmon",
    "salsa",
    "salsify",
    "salt",
    "salt beef",
    "salt cod",
    "sambuca",
    "samphire",
    "sandwich",
    "sardine",
    "sashimi",
    "satsuma",
    "sauces",
    "saucisson",
    "sausage",
    "savory",
    "savoy cabbage",
    "scallop",
    "scotch bonnet chilli",
    "scrag",
    "sea bass",
    "sea bream",
    "sea salt",
    "sea trout",
    "seafood",
    "seasoning",
    "seaweed",
    "seeds",
    "self-raising flour",
    "semolina",
    "serrano ham",
    "sesame oil",
    "sesame seeds",
    "seville orange",
    "shallot",
    "sharon fruit",
    "shellfish",
    "sherry",
    "sherry vinegar",
    "shiitake mushroom",
    "shin",
    "shortbread",
    "shortcrust pastry",
    "sichuan pepper",
    "silverside",
    "single cream",
    "sirloin",
    "skate",
    "sloe",
    "sloe gin",
    "smoked cheese",
    "smoked fish",
    "smoked haddock",
    "smoked mackerel",
    "smoked salmon",
    "smoked trout",
    "snapper",
    "soba noodles",
    "soda",
    "soda bread",
    "sole",
    "sorbet",
    "sorrel",
    "soup",
    "sourdough bread",
    "soured cream",
    "soy sauce",
    "soya beans",
    "soya flour",
    "soya milk",
    "soya oil",
    "spaghetti",
    "spaghetti squash",
    "sparkling wine",
    "spelt",
    "spelt flour",
    "spices",
    "spinach",
    "split peas",
    "sponge cake",
    "spring greens",
    "spring onion",
    "spring roll wrappers",
    "squash",
    "squid",
    "star anise",
    "starfruit",
    "steak",
    "stem ginger",
    "stew",
    "stewing lamb",
    "stilton",
    "stock",
    "straw mushroom",
    "strawberry",
    "strawberry jam",
    "strega liqueur",
    "strong white flour",
    "stuffing",
    "sucralose",
    "suet",
    "sugar",
    "sugar-snap peas",
    "sultanas",
    "sumac",
    "summer cabbage",
    "summer fruit",
    "sunflower oil",
    "sunflower seed",
    "sushi rice",
    "swede",
    "sweet potato",
    "sweet sherry",
    "sweetbread",
    "sweetcorn",
    "swiss chard",
    "swiss rolls and roulades",
    "swordfish",
    "syrup",
    "t-bone steak",
    "tabasco",
    "taco",
    "tagliatelle",
    "tahini",
    "taleggio",
    "tamari",
    "tamarillo",
    "tamarind",
    "tangerine",
    "tapenade",
    "tapioca",
    "taro",
    "tarragon",
    "tartare sauce",
    "tayberry",
    "tea",
    "tempura",
    "tequila",
    "teriyaki",
    "teriyaki sauce",
    "terrine",
    "thai basil",
    "thyme",
    "tilapia",
    "tinned tuna",
    "toffee",
    "tofu",
    "tomato",
    "tomato chutney",
    "tomato juice",
    "tomato purée",
    "tongue",
    "tonic",
    "topside",
    "tortellini",
    "tripe",
    "trout",
    "truffle",
    "truffle oil",
    "turbot",
    "turkey",
    "turkey breast",
    "turkey mince",
    "turkish delight",
    "turmeric",
    "turnip",
    "unleavened bread",
    "vacherin",
    "vanilla essence",
    "vanilla extract",
    "vanilla pod",
    "veal",
    "vegetable oil",
    "vegetable shortening",
    "vegetable stock",
    "vegetables",
    "vegetarian sausage",
    "venison",
    "verjus",
    "vermicelli",
    "vermouth",
    "vine leaves",
    "vinegar",
    "vodka",
    "vodka cocktail",
    "waffles",
    "walnut",
    "walnut oil",
    "wasabi",
    "water chestnut",
    "watercress",
    "watermelon",
    "waxy potato",
    "webbs lettuce",
    "wensleydale",
    "wheatgerm",
    "whelk",
    "whipping cream",
    "whisky",
    "whisky cocktail",
    "whisky liqueur",
    "white bread",
    "white cabbage",
    "white chocolate",
    "white fish",
    "white pepper",
    "white wine",
    "white wine vinegar",
    "whitebait",
    "whitecurrant",
    "whiting",
    "whole wheat pasta",
    "wholegrain mustard",
    "wholemeal bread",
    "wholemeal flour",
    "wild duck",
    "wild garlic",
    "wild mushrooms",
    "wild rice",
    "wine",
    "winkles",
    "wood pigeon",
    "worcestershire sauce",
    "wraps",
    "yam",
    "yeast",
    "yellow lentil",
    "yoghurt",
    "zander",
    "zest"
]

print extract_ingredient_names(curated_ingredient_names)
